// Requirements: 4.2, 8.1, 8.2, 8.3 - App catalog types and sample data

// Operating System Types
export type OSId = 'macos' | 'linux' | 'windows';

export interface OS {
  id: OSId;
  name: string;
  iconUrl: string;
  color: string;
}

// Package Manager Types - Requirements 1.1, 1.2, 2.1
export type PackageManagerId =
  // Windows
  | 'winget'
  | 'chocolatey'
  | 'scoop'
  // macOS
  | 'homebrew'
  | 'macports'
  // Linux
  | 'apt'
  | 'dnf'
  | 'pacman'
  | 'zypper'
  | 'flatpak'
  | 'snap';

export interface PackageManager {
  id: PackageManagerId;
  name: string;
  iconUrl: string;
  color: string;
  installPrefix: string;
  osId: OSId;
  isPrimary?: boolean; // Default package manager for the OS
}

// Category Type - 15 categories as per Requirement 4.2
export type Category =
  | 'Web Browsers'
  | 'Communication'
  | 'Dev: Languages'
  | 'Dev: Editors'
  | 'Dev: Tools'
  | 'Terminal'
  | 'CLI Tools'
  | 'Media'
  | 'Creative'
  | 'Gaming'
  | 'Office'
  | 'VPN & Network'
  | 'Security'
  | 'File Sharing'
  | 'System';

// App Data Type - Requirements 1.3, 1.4, 1.5, 8.2
export interface AppData {
  id: string;
  name: string;
  description: string;
  category: Category;
  iconUrl: string;
  // Maps package manager to package name/command
  targets: Partial<Record<PackageManagerId, string>>;
  // Markdown shown when app unavailable for a package manager
  unavailableReason?: string;
}

// Operating Systems Data
export const operatingSystems: OS[] = [
  {
    id: 'macos',
    name: 'MacOS',
    iconUrl: 'https://api.iconify.design/simple-icons/apple.svg?color=%23999999',
    color: '#999999'
  },
  {
    id: 'linux',
    name: 'Linux',
    iconUrl: 'https://api.iconify.design/simple-icons/linux.svg?color=%23FCC624',
    color: '#FCC624'
  },
  {
    id: 'windows',
    name: 'Windows',
    iconUrl: 'https://api.iconify.design/simple-icons/windows.svg?color=%230078D4',
    color: '#0078D4'
  }
];

// Package Managers Data - Requirements 1.1, 1.2, 2.1
export const packageManagers: PackageManager[] = [
  // Windows
  {
    id: 'winget',
    name: 'Winget',
    iconUrl: 'https://api.iconify.design/simple-icons/windows.svg?color=%230078D4',
    color: '#0078D4',
    installPrefix: 'winget install -e --id',
    osId: 'windows',
    isPrimary: true,
  },
  {
    id: 'chocolatey',
    name: 'Chocolatey',
    iconUrl: 'https://api.iconify.design/simple-icons/chocolatey.svg?color=%2380B5E3',
    color: '#80B5E3',
    installPrefix: 'choco install -y',
    osId: 'windows',
  },
  {
    id: 'scoop',
    name: 'Scoop',
    iconUrl: 'https://api.iconify.design/simple-icons/scoop.svg?color=%23B5E853',
    color: '#B5E853',
    installPrefix: 'scoop install',
    osId: 'windows',
  },
  // macOS
  {
    id: 'homebrew',
    name: 'Homebrew',
    iconUrl: 'https://api.iconify.design/simple-icons/homebrew.svg?color=%23FBB040',
    color: '#FBB040',
    installPrefix: 'brew install',
    osId: 'macos',
    isPrimary: true,
  },
  {
    id: 'macports',
    name: 'MacPorts',
    iconUrl: 'https://api.iconify.design/simple-icons/apple.svg?color=%23999999',
    color: '#999999',
    installPrefix: 'sudo port install',
    osId: 'macos',
  },
  // Linux
  {
    id: 'apt',
    name: 'APT (Debian/Ubuntu)',
    iconUrl: 'https://api.iconify.design/simple-icons/debian.svg?color=%23A81D33',
    color: '#A81D33',
    installPrefix: 'sudo apt install -y',
    osId: 'linux',
    isPrimary: true,
  },
  {
    id: 'dnf',
    name: 'DNF (Fedora)',
    iconUrl: 'https://api.iconify.design/simple-icons/fedora.svg?color=%2351A2DA',
    color: '#51A2DA',
    installPrefix: 'sudo dnf install -y',
    osId: 'linux',
  },
  {
    id: 'pacman',
    name: 'Pacman (Arch)',
    iconUrl: 'https://api.iconify.design/simple-icons/archlinux.svg?color=%231793D1',
    color: '#1793D1',
    installPrefix: 'sudo pacman -S --needed --noconfirm',
    osId: 'linux',
  },
  {
    id: 'zypper',
    name: 'Zypper (openSUSE)',
    iconUrl: 'https://api.iconify.design/simple-icons/opensuse.svg?color=%2373BA25',
    color: '#73BA25',
    installPrefix: 'sudo zypper install -y',
    osId: 'linux',
  },
  {
    id: 'flatpak',
    name: 'Flatpak',
    iconUrl: 'https://api.iconify.design/simple-icons/flatpak.svg?color=%234A90D9',
    color: '#4A90D9',
    installPrefix: 'flatpak install flathub -y',
    osId: 'linux',
  },
  {
    id: 'snap',
    name: 'Snap',
    iconUrl: 'https://api.iconify.design/simple-icons/snapcraft.svg?color=%2382BEA0',
    color: '#82BEA0',
    installPrefix: 'sudo snap install',
    osId: 'linux',
  },
];

// Category Colors for styling
export const categoryColors: Record<Category, string> = {
  'Web Browsers': '#f97316',    // orange
  'Communication': '#3b82f6',   // blue
  'Media': '#eab308',           // yellow
  'Gaming': '#a855f7',          // purple
  'Office': '#6366f1',          // indigo
  'Creative': '#06b6d4',        // cyan
  'System': '#ef4444',          // red
  'File Sharing': '#14b8a6',    // teal
  'Security': '#22c55e',        // green
  'VPN & Network': '#10b981',   // emerald
  'Dev: Editors': '#0ea5e9',    // sky
  'Dev: Languages': '#f43f5e',  // rose
  'Dev: Tools': '#64748b',      // slate
  'Terminal': '#71717a',        // zinc
  'CLI Tools': '#6b7280'        // gray
};

// All categories in display order
export const categories: Category[] = [
  'Web Browsers',
  'Communication',
  'Media',
  'Gaming',
  'Office',
  'Creative',
  'Dev: Editors',
  'Dev: Tools',
  'Dev: Languages',
  'Terminal',
  'CLI Tools',
  'VPN & Network',
  'Security',
  'File Sharing',
  'System'
];

// App Data - Requirements 7.1, 7.2, 7.3, 7.4 - Migrated to targets model
export const apps: AppData[] = [
  // Web Browsers
  {
    id: 'firefox',
    name: 'Firefox',
    description: 'Privacy-focused open-source browser by Mozilla',
    category: 'Web Browsers',
    iconUrl: 'https://api.iconify.design/logos/firefox.svg',
    targets: {
      winget: 'Mozilla.Firefox',
      chocolatey: 'firefox',
      scoop: 'firefox',
      homebrew: '--cask firefox',
      macports: 'firefox',
      apt: 'firefox',
      dnf: 'firefox',
      pacman: 'firefox',
      zypper: 'MozillaFirefox',
      flatpak: 'org.mozilla.firefox',
      snap: 'firefox',
    },
  },
  {
    id: 'chrome',
    name: 'Google Chrome',
    description: 'Fast and popular browser by Google',
    category: 'Web Browsers',
    iconUrl: 'https://api.iconify.design/logos/chrome.svg',
    targets: {
      winget: 'Google.Chrome',
      chocolatey: 'googlechrome',
      scoop: 'googlechrome',
      homebrew: '--cask google-chrome',
      pacman: 'google-chrome',
      flatpak: 'com.google.Chrome',
    },
    unavailableReason: 'Not in official Linux distro repos or MacPorts. Use [Flatpak](https://flathub.org/apps/com.google.Chrome) or download from [google.com/chrome](https://www.google.com/chrome/).',
  },
  {
    id: 'chromium',
    name: 'Chromium',
    description: 'Open-source browser that powers Google Chrome',
    category: 'Web Browsers',
    iconUrl: 'https://api.iconify.design/logos/chrome.svg',
    targets: {
      winget: 'Hibbiki.Chromium',
      chocolatey: 'chromium',
      scoop: 'chromium',
      homebrew: '--cask chromium',
      apt: 'chromium-browser',
      dnf: 'chromium',
      pacman: 'chromium',
      zypper: 'chromium',
      flatpak: 'org.chromium.Chromium',
      snap: 'chromium',
    },
  },
  {
    id: 'brave',
    name: 'Brave',
    description: 'Privacy-first browser with built-in ad blocking',
    category: 'Web Browsers',
    iconUrl: 'https://api.iconify.design/simple-icons/brave.svg?color=%23FB542B',
    targets: {
      winget: 'Brave.Brave',
      chocolatey: 'brave',
      scoop: 'brave',
      homebrew: '--cask brave-browser',
      pacman: 'brave-bin',
      flatpak: 'com.brave.Browser',
      snap: 'brave',
    },
    unavailableReason: 'Not in official Linux distro repos or MacPorts. Use [Flatpak](https://flathub.org/apps/com.brave.Browser), [Snap](https://snapcraft.io/brave), or download from [brave.com](https://brave.com/download/).',
  },
  {
    id: 'edge',
    name: 'Microsoft Edge',
    description: 'Microsoft Chromium-based browser',
    category: 'Web Browsers',
    iconUrl: 'https://api.iconify.design/logos/microsoft-edge.svg',
    targets: {
      winget: 'Microsoft.Edge',
      chocolatey: 'microsoft-edge',
      homebrew: '--cask microsoft-edge',
      flatpak: 'com.microsoft.Edge',
    },
    unavailableReason: 'Not in official Linux distro repos, MacPorts, or Scoop. Use [Flatpak](https://flathub.org/apps/com.microsoft.Edge) or download from [microsoft.com/edge](https://www.microsoft.com/edge).',
  },
  {
    id: 'vivaldi',
    name: 'Vivaldi',
    description: 'Highly customizable browser for power users',
    category: 'Web Browsers',
    iconUrl: 'https://api.iconify.design/simple-icons/vivaldi.svg?color=%23EF3939',
    targets: {
      winget: 'Vivaldi.Vivaldi',
      chocolatey: 'vivaldi',
      scoop: 'vivaldi',
      homebrew: '--cask vivaldi',
      pacman: 'vivaldi',
      flatpak: 'com.vivaldi.Vivaldi',
      snap: 'vivaldi',
    },
    unavailableReason: 'Not in official Linux distro repos or MacPorts. Use [Flatpak](https://flathub.org/apps/com.vivaldi.Vivaldi), [Snap](https://snapcraft.io/vivaldi), or download from [vivaldi.com](https://vivaldi.com/download/).',
  },
  {
    id: 'tor',
    name: 'Tor Browser',
    description: 'Anonymous browsing via the Tor network',
    category: 'Web Browsers',
    iconUrl: 'https://api.iconify.design/simple-icons/torbrowser.svg?color=%237D4698',
    targets: {
      winget: 'TorProject.TorBrowser',
      chocolatey: 'tor-browser',
      scoop: 'tor-browser',
      homebrew: '--cask tor-browser',
      apt: 'torbrowser-launcher',
      pacman: 'torbrowser-launcher',
      dnf: 'torbrowser-launcher',
      flatpak: 'org.torproject.torbrowser-launcher',
    },
    unavailableReason: 'Not in all Linux distro repos. Use [Flatpak](https://flathub.org/apps/org.torproject.torbrowser-launcher) or download from [torproject.org](https://www.torproject.org/download/).',
  },
  {
    id: 'librewolf',
    name: 'LibreWolf',
    description: 'Privacy-hardened Firefox fork with telemetry removed',
    category: 'Web Browsers',
    iconUrl: 'https://api.iconify.design/simple-icons/firefoxbrowser.svg?color=%230588D1',
    targets: {
      winget: 'LibreWolf.LibreWolf',
      chocolatey: 'librewolf',
      scoop: 'librewolf',
      homebrew: '--cask librewolf',
      pacman: 'librewolf-bin',
      flatpak: 'io.gitlab.librewolf-community',
    },
    unavailableReason: 'Not in official Linux distro repos. Use [Flatpak](https://flathub.org/apps/io.gitlab.librewolf-community) or download from [librewolf.net](https://librewolf.net/installation/).',
  },
  
  // Communication
  {
    id: 'discord',
    name: 'Discord',
    description: 'Voice, video, and text chat for communities',
    category: 'Communication',
    iconUrl: 'https://api.iconify.design/logos/discord-icon.svg',
    targets: {
      winget: 'Discord.Discord',
      chocolatey: 'discord',
      scoop: 'discord',
      homebrew: '--cask discord',
      pacman: 'discord',
      flatpak: 'com.discordapp.Discord',
      snap: 'discord',
    },
    unavailableReason: 'Not in official Linux distro repos or MacPorts. Use [Flatpak](https://flathub.org/apps/com.discordapp.Discord), [Snap](https://snapcraft.io/discord), or download from [discord.com](https://discord.com/download).',
  },
  {
    id: 'slack',
    name: 'Slack',
    description: 'Team collaboration and messaging platform',
    category: 'Communication',
    iconUrl: 'https://api.iconify.design/logos/slack-icon.svg',
    targets: {
      winget: 'SlackTechnologies.Slack',
      chocolatey: 'slack',
      scoop: 'slack',
      homebrew: '--cask slack',
      pacman: 'slack-desktop',
      flatpak: 'com.slack.Slack',
      snap: 'slack --classic',
    },
    unavailableReason: 'Not in official Linux distro repos or MacPorts. Use [Flatpak](https://flathub.org/apps/com.slack.Slack), [Snap](https://snapcraft.io/slack), or download from [slack.com](https://slack.com/downloads).',
  },
  {
    id: 'zoom',
    name: 'Zoom',
    description: 'Video conferencing and meetings',
    category: 'Communication',
    iconUrl: 'https://api.iconify.design/simple-icons/zoom.svg?color=%232D8CFF',
    targets: {
      winget: 'Zoom.Zoom',
      chocolatey: 'zoom',
      scoop: 'zoom',
      homebrew: '--cask zoom',
      pacman: 'zoom',
      flatpak: 'us.zoom.Zoom',
      snap: 'zoom-client',
    },
    unavailableReason: 'Not in official Linux distro repos or MacPorts. Use [Flatpak](https://flathub.org/apps/us.zoom.Zoom), [Snap](https://snapcraft.io/zoom-client), or download from [zoom.us](https://zoom.us/download).',
  },
  {
    id: 'telegram',
    name: 'Telegram',
    description: 'Fast and secure messaging app',
    category: 'Communication',
    iconUrl: 'https://api.iconify.design/logos/telegram.svg',
    targets: {
      winget: 'Telegram.TelegramDesktop',
      chocolatey: 'telegram',
      scoop: 'telegram',
      homebrew: '--cask telegram',
      macports: 'telegram-desktop',
      apt: 'telegram-desktop',
      dnf: 'telegram-desktop',
      pacman: 'telegram-desktop',
      zypper: 'telegram-desktop',
      flatpak: 'org.telegram.desktop',
      snap: 'telegram-desktop',
    },
  },
  {
    id: 'signal',
    name: 'Signal',
    description: 'End-to-end encrypted messaging',
    category: 'Communication',
    iconUrl: 'https://api.iconify.design/simple-icons/signal.svg?color=%233A76F0',
    targets: {
      winget: 'OpenWhisperSystems.Signal',
      chocolatey: 'signal',
      homebrew: '--cask signal',
      pacman: 'signal-desktop',
      flatpak: 'org.signal.Signal',
      snap: 'signal-desktop',
    },
    unavailableReason: 'Not in official Linux distro repos, MacPorts, or Scoop. Use [Flatpak](https://flathub.org/apps/org.signal.Signal), [Snap](https://snapcraft.io/signal-desktop), or download from [signal.org](https://signal.org/download/).',
  },
  {
    id: 'thunderbird',
    name: 'Thunderbird',
    description: 'Free email client by Mozilla with calendar',
    category: 'Communication',
    iconUrl: 'https://api.iconify.design/simple-icons/thunderbird.svg?color=%230A84FF',
    targets: {
      winget: 'Mozilla.Thunderbird',
      chocolatey: 'thunderbird',
      scoop: 'thunderbird',
      homebrew: '--cask thunderbird',
      macports: 'thunderbird',
      apt: 'thunderbird',
      dnf: 'thunderbird',
      pacman: 'thunderbird',
      zypper: 'MozillaThunderbird',
      flatpak: 'org.mozilla.Thunderbird',
      snap: 'thunderbird',
    },
  },
  {
    id: 'element',
    name: 'Element',
    description: 'Decentralized Matrix chat client with E2E encryption',
    category: 'Communication',
    iconUrl: 'https://api.iconify.design/simple-icons/element.svg?color=%230DBD8B',
    targets: {
      winget: 'Element.Element',
      chocolatey: 'element-desktop',
      scoop: 'element',
      homebrew: '--cask element',
      pacman: 'element-desktop',
      flatpak: 'im.riot.Riot',
      snap: 'element-desktop',
    },
    unavailableReason: 'Not in official Linux distro repos or MacPorts. Use [Flatpak](https://flathub.org/apps/im.riot.Riot), [Snap](https://snapcraft.io/element-desktop), or download from [element.io](https://element.io/download).',
  },
  {
    id: 'teams',
    name: 'Microsoft Teams',
    description: 'Business communication and collaboration',
    category: 'Communication',
    iconUrl: 'https://api.iconify.design/logos/microsoft-teams.svg',
    targets: {
      winget: 'Microsoft.Teams',
      chocolatey: 'microsoft-teams',
      homebrew: '--cask microsoft-teams',
      flatpak: 'com.github.nickvision.teams',
    },
    unavailableReason: 'Not in official Linux distro repos, MacPorts, or Scoop. Use [Flatpak](https://flathub.org/apps/com.github.nickvision.teams) or the [web app](https://teams.microsoft.com/).',
  },

  // Media
  {
    id: 'vlc',
    name: 'VLC',
    description: 'Free and open-source media player',
    category: 'Media',
    iconUrl: 'https://api.iconify.design/simple-icons/vlcmediaplayer.svg?color=%23FF8800',
    targets: {
      winget: 'VideoLAN.VLC',
      chocolatey: 'vlc',
      scoop: 'vlc',
      homebrew: '--cask vlc',
      macports: 'VLC',
      apt: 'vlc',
      dnf: 'vlc',
      pacman: 'vlc',
      zypper: 'vlc',
      flatpak: 'org.videolan.VLC',
      snap: 'vlc',
    },
  },
  {
    id: 'mpv',
    name: 'mpv',
    description: 'Lightweight and highly configurable media player',
    category: 'Media',
    iconUrl: 'https://api.iconify.design/simple-icons/mpv.svg?color=%23691F69',
    targets: {
      winget: 'mpv.net',
      chocolatey: 'mpv',
      scoop: 'mpv',
      homebrew: 'mpv',
      macports: 'mpv',
      apt: 'mpv',
      dnf: 'mpv',
      pacman: 'mpv',
      zypper: 'mpv',
      flatpak: 'io.mpv.Mpv',
      snap: 'mpv',
    },
  },
  {
    id: 'spotify',
    name: 'Spotify',
    description: 'Music streaming service',
    category: 'Media',
    iconUrl: 'https://api.iconify.design/logos/spotify-icon.svg',
    targets: {
      winget: 'Spotify.Spotify',
      chocolatey: 'spotify',
      scoop: 'spotify',
      homebrew: '--cask spotify',
      pacman: 'spotify',
      flatpak: 'com.spotify.Client',
      snap: 'spotify',
    },
    unavailableReason: 'Not in official Linux distro repos or MacPorts. Use [Flatpak](https://flathub.org/apps/com.spotify.Client), [Snap](https://snapcraft.io/spotify), or download from [spotify.com](https://www.spotify.com/download/).',
  },
  {
    id: 'obs',
    name: 'OBS Studio',
    description: 'Open-source streaming and recording',
    category: 'Media',
    iconUrl: 'https://api.iconify.design/simple-icons/obsstudio.svg?color=%23302E31',
    targets: {
      winget: 'OBSProject.OBSStudio',
      chocolatey: 'obs-studio',
      scoop: 'obs-studio',
      homebrew: '--cask obs',
      macports: 'obs-studio',
      apt: 'obs-studio',
      dnf: 'obs-studio',
      pacman: 'obs-studio',
      zypper: 'obs-studio',
      flatpak: 'com.obsproject.Studio',
      snap: 'obs-studio',
    },
  },
  {
    id: 'handbrake',
    name: 'HandBrake',
    description: 'Open-source video transcoder',
    category: 'Media',
    iconUrl: 'https://api.iconify.design/simple-icons/handbrake.svg?color=%23FF5733',
    targets: {
      winget: 'HandBrake.HandBrake',
      chocolatey: 'handbrake',
      scoop: 'handbrake',
      homebrew: '--cask handbrake',
      macports: 'HandBrake',
      apt: 'handbrake',
      dnf: 'HandBrake',
      pacman: 'handbrake',
      zypper: 'handbrake',
      flatpak: 'fr.handbrake.ghb',
      snap: 'handbrake-jz',
    },
  },
  {
    id: 'kdenlive',
    name: 'Kdenlive',
    description: 'Powerful open-source video editor by KDE',
    category: 'Media',
    iconUrl: 'https://api.iconify.design/simple-icons/kdenlive.svg?color=%23527EB2',
    targets: {
      winget: 'KDE.Kdenlive',
      chocolatey: 'kdenlive',
      scoop: 'kdenlive',
      homebrew: '--cask kdenlive',
      apt: 'kdenlive',
      dnf: 'kdenlive',
      pacman: 'kdenlive',
      zypper: 'kdenlive',
      flatpak: 'org.kde.kdenlive',
      snap: 'kdenlive',
    },
  },
  {
    id: 'ffmpeg',
    name: 'FFmpeg',
    description: 'Swiss army knife of video/audio processing',
    category: 'Media',
    iconUrl: 'https://api.iconify.design/simple-icons/ffmpeg.svg?color=%23007808',
    targets: {
      winget: 'Gyan.FFmpeg',
      chocolatey: 'ffmpeg',
      scoop: 'ffmpeg',
      homebrew: 'ffmpeg',
      macports: 'ffmpeg',
      apt: 'ffmpeg',
      dnf: 'ffmpeg',
      pacman: 'ffmpeg',
      zypper: 'ffmpeg',
    },
    unavailableReason: 'FFmpeg is a CLI tool and not available via Flatpak or Snap.',
  },
  {
    id: 'kodi',
    name: 'Kodi',
    description: 'Open-source home theater and media center',
    category: 'Media',
    iconUrl: 'https://api.iconify.design/simple-icons/kodi.svg?color=%2317B2E7',
    targets: {
      winget: 'XBMCFoundation.Kodi',
      chocolatey: 'kodi',
      scoop: 'kodi',
      homebrew: '--cask kodi',
      apt: 'kodi',
      dnf: 'kodi',
      pacman: 'kodi',
      zypper: 'kodi',
      flatpak: 'tv.kodi.Kodi',
      snap: 'kodi',
    },
  },
  {
    id: 'stremio',
    name: 'Stremio',
    description: 'Modern media center with streaming addons',
    category: 'Media',
    iconUrl: 'https://api.iconify.design/simple-icons/stremio.svg?color=%238A5AAB',
    targets: {
      winget: 'Stremio.Stremio',
      chocolatey: 'stremio',
      homebrew: '--cask stremio',
      pacman: 'stremio',
      flatpak: 'com.stremio.Stremio',
    },
    unavailableReason: 'Not in official Linux distro repos. Use [Flatpak](https://flathub.org/apps/com.stremio.Stremio) or download from [stremio.com](https://www.stremio.com/downloads).',
  },
  
  // Gaming
  {
    id: 'steam',
    name: 'Steam',
    description: 'Digital game distribution platform',
    category: 'Gaming',
    iconUrl: 'https://api.iconify.design/simple-icons/steam.svg?color=%23000000',
    targets: {
      winget: 'Valve.Steam',
      chocolatey: 'steam',
      scoop: 'steam',
      homebrew: '--cask steam',
      apt: 'steam',
      dnf: 'steam',
      pacman: 'steam',
      zypper: 'steam',
      flatpak: 'com.valvesoftware.Steam',
      snap: 'steam',
    },
  },
  {
    id: 'lutris',
    name: 'Lutris',
    description: 'Open gaming platform for Linux',
    category: 'Gaming',
    iconUrl: 'https://api.iconify.design/simple-icons/lutris.svg?color=%23FF9900',
    targets: {
      apt: 'lutris',
      dnf: 'lutris',
      pacman: 'lutris',
      zypper: 'lutris',
      flatpak: 'net.lutris.Lutris',
    },
    unavailableReason: 'Linux-only application. Not available for Windows or macOS.',
  },
  {
    id: 'heroic',
    name: 'Heroic',
    description: 'Epic Games and GOG launcher',
    category: 'Gaming',
    iconUrl: 'https://api.iconify.design/simple-icons/heroicgameslauncher.svg?color=%23FF6B00',
    targets: {
      winget: 'HeroicGamesLauncher.HeroicGamesLauncher',
      chocolatey: 'heroic-games-launcher',
      homebrew: '--cask heroic',
      pacman: 'heroic-games-launcher-bin',
      flatpak: 'com.heroicgameslauncher.hgl',
    },
    unavailableReason: 'Not in official Linux distro repos, MacPorts, or Scoop. Use [Flatpak](https://flathub.org/apps/com.heroicgameslauncher.hgl) or download from [heroicgameslauncher.com](https://heroicgameslauncher.com/).',
  },
  {
    id: 'retroarch',
    name: 'RetroArch',
    description: 'Multi-system emulator frontend',
    category: 'Gaming',
    iconUrl: 'https://api.iconify.design/simple-icons/retroarch.svg?color=%23000000',
    targets: {
      winget: 'Libretro.RetroArch',
      chocolatey: 'retroarch',
      scoop: 'retroarch',
      homebrew: '--cask retroarch',
      macports: 'RetroArch',
      apt: 'retroarch',
      dnf: 'retroarch',
      pacman: 'retroarch',
      zypper: 'retroarch',
      flatpak: 'org.libretro.RetroArch',
      snap: 'retroarch',
    },
  },
  {
    id: 'prism',
    name: 'Prism Launcher',
    description: 'Open-source Minecraft launcher with mod support',
    category: 'Gaming',
    iconUrl: 'https://api.iconify.design/simple-icons/minecraft.svg?color=%2362B47A',
    targets: {
      winget: 'PrismLauncher.PrismLauncher',
      chocolatey: 'prismlauncher',
      scoop: 'prismlauncher',
      homebrew: '--cask prismlauncher',
      pacman: 'prismlauncher',
      flatpak: 'org.prismlauncher.PrismLauncher',
    },
    unavailableReason: 'Not in official Linux distro repos. Use [Flatpak](https://flathub.org/apps/org.prismlauncher.PrismLauncher) or download from [prismlauncher.org](https://prismlauncher.org/download/).',
  },
  {
    id: 'epicgames',
    name: 'Epic Games Launcher',
    description: 'Epic Games Store client',
    category: 'Gaming',
    iconUrl: 'https://api.iconify.design/simple-icons/epicgames.svg?color=%23313131',
    targets: {
      winget: 'EpicGames.EpicGamesLauncher',
      chocolatey: 'epicgameslauncher',
      scoop: 'epic-games-launcher',
    },
    unavailableReason: 'Windows-only application. On Linux, use [Heroic Games Launcher](https://heroicgameslauncher.com/) instead.',
  },
  {
    id: 'gog',
    name: 'GOG Galaxy',
    description: 'GOG.com game launcher',
    category: 'Gaming',
    iconUrl: 'https://api.iconify.design/simple-icons/gogdotcom.svg?color=%2386328A',
    targets: {
      winget: 'GOG.Galaxy',
      chocolatey: 'goggalaxy',
      scoop: 'gog-galaxy',
      homebrew: '--cask gog-galaxy',
    },
    unavailableReason: 'Not available for Linux. Use [Heroic Games Launcher](https://heroicgameslauncher.com/) for GOG games on Linux.',
  },
  
  // Office
  {
    id: 'libreoffice',
    name: 'LibreOffice',
    description: 'Free and open-source office suite',
    category: 'Office',
    iconUrl: 'https://api.iconify.design/simple-icons/libreoffice.svg?color=%2318A303',
    targets: {
      winget: 'TheDocumentFoundation.LibreOffice',
      chocolatey: 'libreoffice-fresh',
      scoop: 'libreoffice',
      homebrew: '--cask libreoffice',
      macports: 'libreoffice',
      apt: 'libreoffice',
      dnf: 'libreoffice',
      pacman: 'libreoffice-fresh',
      zypper: 'libreoffice',
      flatpak: 'org.libreoffice.LibreOffice',
      snap: 'libreoffice',
    },
  },
  {
    id: 'onlyoffice',
    name: 'OnlyOffice',
    description: 'Modern office suite with MS Office compatibility',
    category: 'Office',
    iconUrl: 'https://api.iconify.design/simple-icons/onlyoffice.svg?color=%23FF6F3D',
    targets: {
      winget: 'ONLYOFFICE.DesktopEditors',
      chocolatey: 'onlyoffice',
      scoop: 'onlyoffice-desktopeditors',
      homebrew: '--cask onlyoffice',
      pacman: 'onlyoffice-bin',
      flatpak: 'org.onlyoffice.desktopeditors',
      snap: 'onlyoffice-desktopeditors',
    },
    unavailableReason: 'Not in official Linux distro repos. Use [Flatpak](https://flathub.org/apps/org.onlyoffice.desktopeditors), [Snap](https://snapcraft.io/onlyoffice-desktopeditors), or download from [onlyoffice.com](https://www.onlyoffice.com/desktop.aspx).',
  },
  {
    id: 'notion',
    name: 'Notion',
    description: 'All-in-one workspace for notes and docs',
    category: 'Office',
    iconUrl: 'https://api.iconify.design/simple-icons/notion.svg?color=%23000000',
    targets: {
      winget: 'Notion.Notion',
      chocolatey: 'notion',
      homebrew: '--cask notion',
      snap: 'notion-snap-reborn',
    },
    unavailableReason: 'Not in official Linux distro repos, MacPorts, Scoop, or Flatpak. Use [Snap](https://snapcraft.io/notion-snap-reborn) or the [web app](https://www.notion.so/).',
  },
  {
    id: 'obsidian',
    name: 'Obsidian',
    description: 'Knowledge base and note-taking app',
    category: 'Office',
    iconUrl: 'https://api.iconify.design/simple-icons/obsidian.svg?color=%237C3AED',
    targets: {
      winget: 'Obsidian.Obsidian',
      chocolatey: 'obsidian',
      scoop: 'obsidian',
      homebrew: '--cask obsidian',
      pacman: 'obsidian',
      flatpak: 'md.obsidian.Obsidian',
      snap: 'obsidian --classic',
    },
    unavailableReason: 'Not in official Linux distro repos or MacPorts. Use [Flatpak](https://flathub.org/apps/md.obsidian.Obsidian), [Snap](https://snapcraft.io/obsidian), or download from [obsidian.md](https://obsidian.md/).',
  },
  {
    id: 'logseq',
    name: 'Logseq',
    description: 'Privacy-first knowledge management',
    category: 'Office',
    iconUrl: 'https://api.iconify.design/simple-icons/logseq.svg?color=%2385C8C8',
    targets: {
      winget: 'Logseq.Logseq',
      chocolatey: 'logseq',
      scoop: 'logseq',
      homebrew: '--cask logseq',
      pacman: 'logseq-desktop-bin',
      flatpak: 'com.logseq.Logseq',
      snap: 'logseq',
    },
    unavailableReason: 'Not in official Linux distro repos or MacPorts. Use [Flatpak](https://flathub.org/apps/com.logseq.Logseq) or download from [logseq.com](https://logseq.com/).',
  },
  {
    id: 'joplin',
    name: 'Joplin',
    description: 'Open-source note-taking with sync and encryption',
    category: 'Office',
    iconUrl: 'https://api.iconify.design/simple-icons/joplin.svg?color=%231471B7',
    targets: {
      winget: 'Joplin.Joplin',
      chocolatey: 'joplin',
      scoop: 'joplin',
      homebrew: '--cask joplin',
      pacman: 'joplin-appimage',
      flatpak: 'net.cozic.joplin_desktop',
      snap: 'joplin-desktop',
    },
    unavailableReason: 'Not in official Linux distro repos. Use [Flatpak](https://flathub.org/apps/net.cozic.joplin_desktop), [Snap](https://snapcraft.io/joplin-desktop), or download from [joplinapp.org](https://joplinapp.org/).',
  },
  {
    id: 'calibre',
    name: 'Calibre',
    description: 'Complete e-book library management solution',
    category: 'Office',
    iconUrl: 'https://api.iconify.design/simple-icons/calibreweb.svg?color=%23ECA315',
    targets: {
      winget: 'calibre.calibre',
      chocolatey: 'calibre',
      scoop: 'calibre',
      homebrew: '--cask calibre',
      apt: 'calibre',
      dnf: 'calibre',
      pacman: 'calibre',
      zypper: 'calibre',
      flatpak: 'com.calibre_ebook.calibre',
    },
  },
  {
    id: 'okular',
    name: 'Okular',
    description: 'Universal document viewer by KDE',
    category: 'Office',
    iconUrl: 'https://api.iconify.design/simple-icons/kde.svg?color=%23338BDB',
    targets: {
      winget: 'KDE.Okular',
      chocolatey: 'okular',
      scoop: 'okular',
      homebrew: '--cask okular',
      apt: 'okular',
      dnf: 'okular',
      pacman: 'okular',
      zypper: 'okular',
      flatpak: 'org.kde.okular',
      snap: 'okular',
    },
  },

  // Creative
  {
    id: 'gimp',
    name: 'GIMP',
    description: 'Free and open-source image editor',
    category: 'Creative',
    iconUrl: 'https://api.iconify.design/simple-icons/gimp.svg?color=%235C5543',
    targets: {
      winget: 'GIMP.GIMP',
      chocolatey: 'gimp',
      scoop: 'gimp',
      homebrew: '--cask gimp',
      macports: 'gimp',
      apt: 'gimp',
      dnf: 'gimp',
      pacman: 'gimp',
      zypper: 'gimp',
      flatpak: 'org.gimp.GIMP',
      snap: 'gimp',
    },
  },
  {
    id: 'inkscape',
    name: 'Inkscape',
    description: 'Professional vector graphics editor',
    category: 'Creative',
    iconUrl: 'https://api.iconify.design/simple-icons/inkscape.svg?color=%23000000',
    targets: {
      winget: 'Inkscape.Inkscape',
      chocolatey: 'inkscape',
      scoop: 'inkscape',
      homebrew: '--cask inkscape',
      macports: 'inkscape',
      apt: 'inkscape',
      dnf: 'inkscape',
      pacman: 'inkscape',
      zypper: 'inkscape',
      flatpak: 'org.inkscape.Inkscape',
      snap: 'inkscape',
    },
  },
  {
    id: 'blender',
    name: 'Blender',
    description: '3D creation suite',
    category: 'Creative',
    iconUrl: 'https://api.iconify.design/logos/blender.svg',
    targets: {
      winget: 'BlenderFoundation.Blender',
      chocolatey: 'blender',
      scoop: 'blender',
      homebrew: '--cask blender',
      macports: 'blender',
      apt: 'blender',
      dnf: 'blender',
      pacman: 'blender',
      zypper: 'blender',
      flatpak: 'org.blender.Blender',
      snap: 'blender --classic',
    },
  },
  {
    id: 'krita',
    name: 'Krita',
    description: 'Professional digital painting application',
    category: 'Creative',
    iconUrl: 'https://api.iconify.design/simple-icons/krita.svg?color=%23337FCC',
    targets: {
      winget: 'KDE.Krita',
      chocolatey: 'krita',
      scoop: 'krita',
      homebrew: '--cask krita',
      apt: 'krita',
      dnf: 'krita',
      pacman: 'krita',
      zypper: 'krita',
      flatpak: 'org.kde.krita',
      snap: 'krita',
    },
  },
  {
    id: 'figma',
    name: 'Figma',
    description: 'Collaborative design tool',
    category: 'Creative',
    iconUrl: 'https://api.iconify.design/logos/figma.svg',
    targets: {
      winget: 'Figma.Figma',
      chocolatey: 'figma',
      homebrew: '--cask figma',
      flatpak: 'io.github.nickvision.figma',
      snap: 'figma-linux',
    },
    unavailableReason: 'Not in official Linux distro repos, MacPorts, or Scoop. Use [Flatpak](https://flathub.org/apps/io.github.nickvision.figma), [Snap](https://snapcraft.io/figma-linux), or the [web app](https://www.figma.com/).',
  },
  {
    id: 'audacity',
    name: 'Audacity',
    description: 'Free audio editor and recorder',
    category: 'Creative',
    iconUrl: 'https://api.iconify.design/simple-icons/audacity.svg?color=%230000CC',
    targets: {
      winget: 'Audacity.Audacity',
      chocolatey: 'audacity',
      scoop: 'audacity',
      homebrew: '--cask audacity',
      macports: 'audacity',
      apt: 'audacity',
      dnf: 'audacity',
      pacman: 'audacity',
      zypper: 'audacity',
      flatpak: 'org.audacityteam.Audacity',
      snap: 'audacity',
    },
  },
  {
    id: 'darktable',
    name: 'Darktable',
    description: 'Professional photography workflow application',
    category: 'Creative',
    iconUrl: 'https://api.iconify.design/simple-icons/darktable.svg?color=%23425D00',
    targets: {
      winget: 'darktable.darktable',
      chocolatey: 'darktable',
      scoop: 'darktable',
      homebrew: '--cask darktable',
      apt: 'darktable',
      dnf: 'darktable',
      pacman: 'darktable',
      zypper: 'darktable',
      flatpak: 'org.darktable.Darktable',
      snap: 'darktable',
    },
  },
  {
    id: 'freecad',
    name: 'FreeCAD',
    description: 'Open-source parametric 3D CAD modeler',
    category: 'Creative',
    iconUrl: 'https://api.iconify.design/simple-icons/freecad.svg?color=%23CB333B',
    targets: {
      winget: 'FreeCAD.FreeCAD',
      chocolatey: 'freecad',
      scoop: 'freecad',
      homebrew: '--cask freecad',
      apt: 'freecad',
      dnf: 'freecad',
      pacman: 'freecad',
      zypper: 'freecad',
      flatpak: 'org.freecad.FreeCAD',
      snap: 'freecad',
    },
  },
  {
    id: 'godot',
    name: 'Godot Engine',
    description: 'Feature-packed, cross-platform game engine',
    category: 'Creative',
    iconUrl: 'https://api.iconify.design/simple-icons/godotengine.svg?color=%23478CBF',
    targets: {
      winget: 'GodotEngine.GodotEngine',
      chocolatey: 'godot',
      scoop: 'godot',
      homebrew: '--cask godot',
      apt: 'godot',
      dnf: 'godot',
      pacman: 'godot',
      flatpak: 'org.godotengine.Godot',
      snap: 'godot-4',
    },
  },
  
  // Dev: Editors
  {
    id: 'vscode',
    name: 'VS Code',
    description: 'Popular extensible code editor by Microsoft',
    category: 'Dev: Editors',
    iconUrl: 'https://api.iconify.design/logos/visual-studio-code.svg',
    targets: {
      winget: 'Microsoft.VisualStudioCode',
      chocolatey: 'vscode',
      scoop: 'vscode',
      homebrew: '--cask visual-studio-code',
      pacman: 'code',
      flatpak: 'com.visualstudio.code',
      snap: 'code --classic',
    },
    unavailableReason: 'Not in official Linux distro repos or MacPorts. Use [Flatpak](https://flathub.org/apps/com.visualstudio.code), [Snap](https://snapcraft.io/code), or download from [code.visualstudio.com](https://code.visualstudio.com/Download).',
  },
  {
    id: 'vscodium',
    name: 'VSCodium',
    description: 'Community-built VS Code without Microsoft telemetry',
    category: 'Dev: Editors',
    iconUrl: 'https://api.iconify.design/simple-icons/vscodium.svg?color=%232F80ED',
    targets: {
      winget: 'VSCodium.VSCodium',
      chocolatey: 'vscodium',
      scoop: 'vscodium',
      homebrew: '--cask vscodium',
      pacman: 'vscodium-bin',
      flatpak: 'com.vscodium.codium',
      snap: 'codium --classic',
    },
    unavailableReason: 'Not in official Linux distro repos or MacPorts. Use [Flatpak](https://flathub.org/apps/com.vscodium.codium), [Snap](https://snapcraft.io/codium), or download from [vscodium.com](https://vscodium.com/).',
  },
  {
    id: 'cursor',
    name: 'Cursor',
    description: 'AI-powered code editor',
    category: 'Dev: Editors',
    iconUrl: 'https://api.iconify.design/simple-icons/cursor.svg?color=%23000000',
    targets: {
      winget: 'Anysphere.Cursor',
      chocolatey: 'cursor',
      homebrew: '--cask cursor',
      pacman: 'cursor-bin',
    },
    unavailableReason: 'Not in official Linux distro repos, MacPorts, Scoop, Flatpak, or Snap. Download from [cursor.sh](https://cursor.sh/).',
  },
  {
    id: 'zed',
    name: 'Zed',
    description: 'High-performance code editor',
    category: 'Dev: Editors',
    iconUrl: 'https://api.iconify.design/simple-icons/zedindustries.svg?color=%23084CCF',
    targets: {
      homebrew: '--cask zed',
      pacman: 'zed',
      flatpak: 'dev.zed.Zed',
    },
    unavailableReason: 'Currently only available for macOS and Linux. Not available for Windows. Use [Homebrew](https://formulae.brew.sh/cask/zed) on macOS or [Flatpak](https://flathub.org/apps/dev.zed.Zed) on Linux.',
  },
  {
    id: 'vim',
    name: 'Vim',
    description: 'The classic modal text editor',
    category: 'Dev: Editors',
    iconUrl: 'https://api.iconify.design/simple-icons/vim.svg?color=%23019733',
    targets: {
      winget: 'vim.vim',
      chocolatey: 'vim',
      scoop: 'vim',
      homebrew: 'vim',
      macports: 'vim',
      apt: 'vim',
      dnf: 'vim-enhanced',
      pacman: 'vim',
      zypper: 'vim',
      flatpak: 'org.vim.Vim',
      snap: 'vim-editor',
    },
  },
  {
    id: 'neovim',
    name: 'Neovim',
    description: 'Hyperextensible Vim-based editor',
    category: 'Dev: Editors',
    iconUrl: 'https://api.iconify.design/simple-icons/neovim.svg?color=%2357A143',
    targets: {
      winget: 'Neovim.Neovim',
      chocolatey: 'neovim',
      scoop: 'neovim',
      homebrew: 'neovim',
      macports: 'neovim',
      apt: 'neovim',
      dnf: 'neovim',
      pacman: 'neovim',
      zypper: 'neovim',
      flatpak: 'io.neovim.nvim',
      snap: 'nvim --classic',
    },
  },
  {
    id: 'helix',
    name: 'Helix',
    description: 'Modal editor with LSP and tree-sitter built-in',
    category: 'Dev: Editors',
    iconUrl: 'https://api.iconify.design/mdi/dna.svg?color=%234E2F7F',
    targets: {
      winget: 'Helix.Helix',
      chocolatey: 'helix',
      scoop: 'helix',
      homebrew: 'helix',
      pacman: 'helix',
      dnf: 'helix',
      flatpak: 'com.helix-editor.Helix',
      snap: 'helix --classic',
    },
    unavailableReason: 'Not in official Debian/Ubuntu repos. Use [Flatpak](https://flathub.org/apps/com.helix-editor.Helix), [Snap](https://snapcraft.io/helix), or download from [helix-editor.com](https://helix-editor.com/).',
  },
  {
    id: 'sublime',
    name: 'Sublime Text',
    description: 'Sophisticated text editor',
    category: 'Dev: Editors',
    iconUrl: 'https://api.iconify.design/simple-icons/sublimetext.svg?color=%23FF9800',
    targets: {
      winget: 'SublimeHQ.SublimeText.4',
      chocolatey: 'sublimetext4',
      scoop: 'sublime-text',
      homebrew: '--cask sublime-text',
      macports: 'sublime-text',
      pacman: 'sublime-text-4',
      flatpak: 'com.sublimetext.three',
      snap: 'sublime-text --classic',
    },
    unavailableReason: 'Not in official Linux distro repos. Use [Flatpak](https://flathub.org/apps/com.sublimetext.three), [Snap](https://snapcraft.io/sublime-text), or download from [sublimetext.com](https://www.sublimetext.com/).',
  },
  {
    id: 'emacs',
    name: 'Emacs',
    description: 'Extensible, customizable, free/libre text editor',
    category: 'Dev: Editors',
    iconUrl: 'https://api.iconify.design/simple-icons/gnuemacs.svg?color=%237F5AB6',
    targets: {
      winget: 'GNU.Emacs',
      chocolatey: 'emacs',
      scoop: 'emacs',
      homebrew: '--cask emacs',
      macports: 'emacs',
      apt: 'emacs',
      dnf: 'emacs',
      pacman: 'emacs',
      zypper: 'emacs',
      flatpak: 'org.gnu.emacs',
      snap: 'emacs --classic',
    },
  },
  {
    id: 'kate',
    name: 'Kate',
    description: 'Feature-rich text editor by KDE',
    category: 'Dev: Editors',
    iconUrl: 'https://api.iconify.design/simple-icons/kde.svg?color=%231D99F3',
    targets: {
      winget: 'KDE.Kate',
      chocolatey: 'kate',
      scoop: 'kate',
      homebrew: '--cask kate',
      apt: 'kate',
      dnf: 'kate',
      pacman: 'kate',
      zypper: 'kate',
      flatpak: 'org.kde.kate',
      snap: 'kate --classic',
    },
  },

  // Dev: Tools
  {
    id: 'docker',
    name: 'Docker',
    description: 'Container platform for developers',
    category: 'Dev: Tools',
    iconUrl: 'https://api.iconify.design/logos/docker-icon.svg',
    targets: {
      winget: 'Docker.DockerDesktop',
      chocolatey: 'docker-desktop',
      scoop: 'docker',
      homebrew: '--cask docker',
      apt: 'docker.io',
      dnf: 'docker',
      pacman: 'docker',
      zypper: 'docker',
      snap: 'docker',
    },
    unavailableReason: 'Docker Desktop is proprietary. On Linux, use the open-source Docker Engine from official repos. On macOS, use [Homebrew](https://formulae.brew.sh/cask/docker) or download from [docker.com](https://www.docker.com/products/docker-desktop/).',
  },
  {
    id: 'podman',
    name: 'Podman',
    description: 'Rootless container engine, Docker alternative',
    category: 'Dev: Tools',
    iconUrl: 'https://api.iconify.design/simple-icons/podman.svg?color=%23892CA0',
    targets: {
      winget: 'RedHat.Podman',
      chocolatey: 'podman-cli',
      homebrew: 'podman',
      apt: 'podman',
      dnf: 'podman',
      pacman: 'podman',
      zypper: 'podman',
    },
    unavailableReason: 'Podman is a system package and not available via Flatpak or Snap.',
  },
  {
    id: 'postman',
    name: 'Postman',
    description: 'API development and testing platform',
    category: 'Dev: Tools',
    iconUrl: 'https://api.iconify.design/simple-icons/postman.svg?color=%23FF6C37',
    targets: {
      winget: 'Postman.Postman',
      chocolatey: 'postman',
      scoop: 'postman',
      homebrew: '--cask postman',
      pacman: 'postman-bin',
      flatpak: 'com.getpostman.Postman',
      snap: 'postman',
    },
    unavailableReason: 'Not in official Linux distro repos or MacPorts. Use [Flatpak](https://flathub.org/apps/com.getpostman.Postman), [Snap](https://snapcraft.io/postman), or download from [postman.com](https://www.postman.com/downloads/).',
  },
  {
    id: 'insomnia',
    name: 'Insomnia',
    description: 'API client for REST and GraphQL',
    category: 'Dev: Tools',
    iconUrl: 'https://api.iconify.design/simple-icons/insomnia.svg?color=%234000BF',
    targets: {
      winget: 'Insomnia.Insomnia',
      chocolatey: 'insomnia-rest-api-client',
      scoop: 'insomnia',
      homebrew: '--cask insomnia',
      flatpak: 'rest.insomnia.Insomnia',
      snap: 'insomnia',
    },
    unavailableReason: 'Not in official Linux distro repos or MacPorts. Use [Flatpak](https://flathub.org/apps/rest.insomnia.Insomnia), [Snap](https://snapcraft.io/insomnia), or download from [insomnia.rest](https://insomnia.rest/download).',
  },
  {
    id: 'bruno',
    name: 'Bruno',
    description: 'Offline-first open-source API client',
    category: 'Dev: Tools',
    iconUrl: 'https://api.iconify.design/mdi/api.svg?color=%23F4A62A',
    targets: {
      winget: 'Bruno.Bruno',
      chocolatey: 'bruno',
      scoop: 'bruno',
      homebrew: '--cask bruno',
      pacman: 'bruno-bin',
      flatpak: 'com.usebruno.Bruno',
      snap: 'bruno',
    },
    unavailableReason: 'Not in official Linux distro repos. Use [Flatpak](https://flathub.org/apps/com.usebruno.Bruno), [Snap](https://snapcraft.io/bruno), or download from [usebruno.com](https://www.usebruno.com/downloads).',
  },
  {
    id: 'dbeaver',
    name: 'DBeaver',
    description: 'Universal database tool',
    category: 'Dev: Tools',
    iconUrl: 'https://api.iconify.design/simple-icons/dbeaver.svg?color=%23382923',
    targets: {
      winget: 'dbeaver.dbeaver',
      chocolatey: 'dbeaver',
      scoop: 'dbeaver',
      homebrew: '--cask dbeaver-community',
      macports: 'dbeaver-community',
      pacman: 'dbeaver',
      flatpak: 'io.dbeaver.DBeaverCommunity',
      snap: 'dbeaver-ce',
    },
    unavailableReason: 'Not in official Linux distro repos. Use [Flatpak](https://flathub.org/apps/io.dbeaver.DBeaverCommunity), [Snap](https://snapcraft.io/dbeaver-ce), or download from [dbeaver.io](https://dbeaver.io/download/).',
  },
  {
    id: 'virtualbox',
    name: 'VirtualBox',
    description: 'Free cross-platform virtual machine manager',
    category: 'Dev: Tools',
    iconUrl: 'https://api.iconify.design/simple-icons/virtualbox.svg?color=%23183A61',
    targets: {
      winget: 'Oracle.VirtualBox',
      chocolatey: 'virtualbox',
      scoop: 'virtualbox',
      homebrew: '--cask virtualbox',
      apt: 'virtualbox',
      pacman: 'virtualbox',
      zypper: 'virtualbox',
    },
    unavailableReason: 'VirtualBox requires kernel modules and is not available via Flatpak or Snap. Download from [virtualbox.org](https://www.virtualbox.org/wiki/Downloads).',
  },
  {
    id: 'meld',
    name: 'Meld',
    description: 'Visual diff and merge tool for files',
    category: 'Dev: Tools',
    iconUrl: 'https://api.iconify.design/simple-icons/gnome.svg?color=%234A86CF',
    targets: {
      winget: 'Meld.Meld',
      chocolatey: 'meld',
      scoop: 'meld',
      homebrew: '--cask meld',
      apt: 'meld',
      dnf: 'meld',
      pacman: 'meld',
      zypper: 'meld',
      flatpak: 'org.gnome.meld',
    },
  },
  {
    id: 'lazygit',
    name: 'LazyGit',
    description: 'Simple terminal UI for git commands',
    category: 'Dev: Tools',
    iconUrl: 'https://api.iconify.design/simple-icons/git.svg?color=%23F05032',
    targets: {
      winget: 'JesseDuffield.lazygit',
      chocolatey: 'lazygit',
      scoop: 'lazygit',
      homebrew: 'lazygit',
      apt: 'lazygit',
      dnf: 'lazygit',
      pacman: 'lazygit',
      zypper: 'lazygit',
    },
  },
  {
    id: 'cmake',
    name: 'CMake',
    description: 'Cross-platform build system generator',
    category: 'Dev: Tools',
    iconUrl: 'https://api.iconify.design/simple-icons/cmake.svg?color=%23064F8C',
    targets: {
      winget: 'Kitware.CMake',
      chocolatey: 'cmake',
      scoop: 'cmake',
      homebrew: 'cmake',
      macports: 'cmake',
      apt: 'cmake',
      dnf: 'cmake',
      pacman: 'cmake',
      zypper: 'cmake',
      snap: 'cmake --classic',
    },
  },
  
  // Dev: Languages
  {
    id: 'nodejs',
    name: 'Node.js',
    description: 'JavaScript runtime environment',
    category: 'Dev: Languages',
    iconUrl: 'https://api.iconify.design/logos/nodejs-icon.svg',
    targets: {
      winget: 'OpenJS.NodeJS.LTS',
      chocolatey: 'nodejs-lts',
      scoop: 'nodejs-lts',
      homebrew: 'node',
      macports: 'nodejs20',
      apt: 'nodejs',
      dnf: 'nodejs',
      pacman: 'nodejs',
      zypper: 'nodejs',
      snap: 'node --classic',
    },
  },
  {
    id: 'python',
    name: 'Python',
    description: 'Popular programming language',
    category: 'Dev: Languages',
    iconUrl: 'https://api.iconify.design/logos/python.svg',
    targets: {
      winget: 'Python.Python.3.12',
      chocolatey: 'python',
      scoop: 'python',
      homebrew: 'python@3.12',
      macports: 'python312',
      apt: 'python3',
      dnf: 'python3',
      pacman: 'python',
      zypper: 'python3',
    },
  },
  {
    id: 'rust',
    name: 'Rust',
    description: 'Systems programming language',
    category: 'Dev: Languages',
    iconUrl: 'https://api.iconify.design/simple-icons/rust.svg?color=%23000000',
    targets: {
      winget: 'Rustlang.Rustup',
      chocolatey: 'rustup.install',
      scoop: 'rustup',
      homebrew: 'rustup-init',
      macports: 'rust',
      pacman: 'rustup',
      dnf: 'rustup',
      zypper: 'rustup',
      snap: 'rustup --classic',
    },
    unavailableReason: 'Install via [rustup.rs](https://rustup.rs) on Ubuntu and Debian.',
  },
  {
    id: 'go',
    name: 'Go',
    description: 'Fast compiled language by Google',
    category: 'Dev: Languages',
    iconUrl: 'https://api.iconify.design/logos/go.svg',
    targets: {
      winget: 'GoLang.Go',
      chocolatey: 'golang',
      scoop: 'go',
      homebrew: 'go',
      macports: 'go',
      apt: 'golang',
      dnf: 'golang',
      pacman: 'go',
      zypper: 'go',
      snap: 'go --classic',
    },
  },
  {
    id: 'java',
    name: 'Java (OpenJDK)',
    description: 'Enterprise programming language',
    category: 'Dev: Languages',
    iconUrl: 'https://api.iconify.design/logos/java.svg',
    targets: {
      winget: 'EclipseAdoptium.Temurin.21.JDK',
      chocolatey: 'temurin21',
      scoop: 'temurin-lts-jdk',
      homebrew: 'openjdk',
      macports: 'openjdk21',
      apt: 'openjdk-21-jdk',
      dnf: 'java-21-openjdk-devel',
      pacman: 'jdk-openjdk',
      zypper: 'java-21-openjdk-devel',
    },
  },
  {
    id: 'ruby',
    name: 'Ruby',
    description: 'Dynamic language known for elegant syntax',
    category: 'Dev: Languages',
    iconUrl: 'https://api.iconify.design/simple-icons/ruby.svg?color=%23CC342D',
    targets: {
      winget: 'RubyInstallerTeam.Ruby.3.2',
      chocolatey: 'ruby',
      scoop: 'ruby',
      homebrew: 'ruby',
      macports: 'ruby',
      apt: 'ruby',
      dnf: 'ruby',
      pacman: 'ruby',
      zypper: 'ruby',
      snap: 'ruby --classic',
    },
  },
  {
    id: 'php',
    name: 'PHP',
    description: 'Popular web server-side scripting language',
    category: 'Dev: Languages',
    iconUrl: 'https://api.iconify.design/simple-icons/php.svg?color=%23777BB4',
    targets: {
      winget: 'PHP.PHP',
      chocolatey: 'php',
      scoop: 'php',
      homebrew: 'php',
      macports: 'php',
      apt: 'php',
      dnf: 'php',
      pacman: 'php',
      zypper: 'php8',
    },
  },
  {
    id: 'deno',
    name: 'Deno',
    description: 'Secure TypeScript/JavaScript runtime',
    category: 'Dev: Languages',
    iconUrl: 'https://api.iconify.design/simple-icons/deno.svg?color=%2370FFAF',
    targets: {
      winget: 'DenoLand.Deno',
      chocolatey: 'deno',
      scoop: 'deno',
      homebrew: 'deno',
      pacman: 'deno',
    },
    unavailableReason: 'Install via `curl -fsSL https://deno.land/install.sh | sh` on other distros.',
  },
  {
    id: 'bun',
    name: 'Bun',
    description: 'Ultra-fast JavaScript runtime and bundler',
    category: 'Dev: Languages',
    iconUrl: 'https://api.iconify.design/logos/bun.svg',
    targets: {
      winget: 'Oven-sh.Bun',
      scoop: 'bun',
      homebrew: 'bun',
      pacman: 'bun',
    },
    unavailableReason: 'Install via `curl -fsSL https://bun.sh/install | bash`. See [bun.sh](https://bun.sh/).',
  },
  {
    id: 'pnpm',
    name: 'pnpm',
    description: 'Fast, disk space efficient package manager',
    category: 'Dev: Languages',
    iconUrl: 'https://api.iconify.design/logos/pnpm.svg',
    targets: {
      winget: 'pnpm.pnpm',
      chocolatey: 'pnpm',
      scoop: 'pnpm',
      homebrew: 'pnpm',
      pacman: 'pnpm',
      dnf: 'pnpm',
    },
    unavailableReason: 'Install via `curl -fsSL https://get.pnpm.io/install.sh | sh`. See [pnpm.io](https://pnpm.io/installation).',
  },

  // Terminal
  {
    id: 'iterm2',
    name: 'iTerm2',
    description: 'Terminal emulator for macOS',
    category: 'Terminal',
    iconUrl: 'https://api.iconify.design/simple-icons/iterm2.svg?color=%23000000',
    targets: {
      homebrew: '--cask iterm2',
      macports: 'iTerm2',
    },
    unavailableReason: 'macOS-only application. Not available for Windows or Linux.',
  },
  {
    id: 'alacritty',
    name: 'Alacritty',
    description: 'GPU-accelerated terminal emulator',
    category: 'Terminal',
    iconUrl: 'https://api.iconify.design/simple-icons/alacritty.svg?color=%23F46D01',
    targets: {
      winget: 'Alacritty.Alacritty',
      chocolatey: 'alacritty',
      scoop: 'alacritty',
      homebrew: '--cask alacritty',
      macports: 'alacritty',
      apt: 'alacritty',
      dnf: 'alacritty',
      pacman: 'alacritty',
      zypper: 'alacritty',
      snap: 'alacritty --classic',
    },
  },
  {
    id: 'wezterm',
    name: 'WezTerm',
    description: 'GPU-accelerated terminal with Lua config',
    category: 'Terminal',
    iconUrl: 'https://api.iconify.design/simple-icons/wezterm.svg?color=%234E49EE',
    targets: {
      winget: 'wez.wezterm',
      chocolatey: 'wezterm',
      scoop: 'wezterm',
      homebrew: '--cask wezterm',
      macports: 'wezterm',
      pacman: 'wezterm',
      flatpak: 'org.wezfurlong.wezterm',
    },
    unavailableReason: 'Not in official Linux distro repos. Use [Flatpak](https://flathub.org/apps/org.wezfurlong.wezterm) or download from [wezfurlong.org/wezterm](https://wezfurlong.org/wezterm/install/linux.html).',
  },
  {
    id: 'kitty',
    name: 'Kitty',
    description: 'Fast GPU-based terminal emulator',
    category: 'Terminal',
    iconUrl: 'https://api.iconify.design/mdi/cat.svg?color=%23ea5e5e',
    targets: {
      homebrew: '--cask kitty',
      macports: 'kitty',
      apt: 'kitty',
      dnf: 'kitty',
      pacman: 'kitty',
      zypper: 'kitty',
    },
    unavailableReason: 'Not available for Windows. Use on macOS or Linux.',
  },
  {
    id: 'windowsterminal',
    name: 'Windows Terminal',
    description: 'Modern terminal for Windows',
    category: 'Terminal',
    iconUrl: 'https://api.iconify.design/simple-icons/windowsterminal.svg?color=%234D4D4D',
    targets: {
      winget: 'Microsoft.WindowsTerminal',
      chocolatey: 'microsoft-windows-terminal',
      scoop: 'windows-terminal',
    },
    unavailableReason: 'Windows-only application. Not available for macOS or Linux.',
  },
  {
    id: 'zsh',
    name: 'Zsh',
    description: 'Powerful shell with advanced completion features',
    category: 'Terminal',
    iconUrl: 'https://api.iconify.design/simple-icons/zsh.svg?color=%23F15A24',
    targets: {
      homebrew: 'zsh',
      macports: 'zsh',
      apt: 'zsh',
      dnf: 'zsh',
      pacman: 'zsh',
      zypper: 'zsh',
    },
    unavailableReason: 'Zsh is a system shell and not available via Flatpak, Snap, or Windows package managers.',
  },
  {
    id: 'fish',
    name: 'Fish',
    description: 'Smart and user-friendly interactive shell',
    category: 'Terminal',
    iconUrl: 'https://api.iconify.design/vscode-icons/file-type-shell.svg',
    targets: {
      homebrew: 'fish',
      macports: 'fish',
      apt: 'fish',
      dnf: 'fish',
      pacman: 'fish',
      zypper: 'fish',
    },
    unavailableReason: 'Fish is a system shell and not available via Flatpak, Snap, or Windows package managers.',
  },
  {
    id: 'starship',
    name: 'Starship',
    description: 'Cross-shell customizable command prompt',
    category: 'Terminal',
    iconUrl: 'https://api.iconify.design/simple-icons/starship.svg?color=%23DD0B78',
    targets: {
      winget: 'Starship.Starship',
      chocolatey: 'starship',
      scoop: 'starship',
      homebrew: 'starship',
      apt: 'starship',
      pacman: 'starship',
      zypper: 'starship',
    },
    unavailableReason: 'Not in Fedora repos. Install via `curl -sS https://starship.rs/install.sh | sh` or see [starship.rs](https://starship.rs/).',
  },
  {
    id: 'powershell',
    name: 'PowerShell',
    description: 'Cross-platform task automation shell',
    category: 'Terminal',
    iconUrl: 'https://api.iconify.design/simple-icons/powershell.svg?color=%235391FE',
    targets: {
      winget: 'Microsoft.PowerShell',
      chocolatey: 'powershell-core',
      scoop: 'pwsh',
      homebrew: '--cask powershell',
      apt: 'powershell',
      dnf: 'powershell',
      pacman: 'powershell-bin',
      snap: 'powershell --classic',
    },
  },
  
  // CLI Tools
  {
    id: 'git',
    name: 'Git',
    description: 'Distributed version control system',
    category: 'CLI Tools',
    iconUrl: 'https://api.iconify.design/logos/git-icon.svg',
    targets: {
      winget: 'Git.Git',
      chocolatey: 'git',
      scoop: 'git',
      homebrew: 'git',
      macports: 'git',
      apt: 'git',
      dnf: 'git',
      pacman: 'git',
      zypper: 'git',
    },
  },
  {
    id: 'gh',
    name: 'GitHub CLI',
    description: 'GitHub from the command line',
    category: 'CLI Tools',
    iconUrl: 'https://api.iconify.design/simple-icons/github.svg?color=%23181717',
    targets: {
      winget: 'GitHub.cli',
      chocolatey: 'gh',
      scoop: 'gh',
      homebrew: 'gh',
      macports: 'gh',
      apt: 'gh',
      dnf: 'gh',
      pacman: 'github-cli',
      zypper: 'gh',
      snap: 'gh',
    },
  },
  {
    id: 'fzf',
    name: 'fzf',
    description: 'Command-line fuzzy finder',
    category: 'CLI Tools',
    iconUrl: 'https://api.iconify.design/mdi/magnify.svg?color=%23FF0055',
    targets: {
      winget: 'junegunn.fzf',
      chocolatey: 'fzf',
      scoop: 'fzf',
      homebrew: 'fzf',
      macports: 'fzf',
      apt: 'fzf',
      dnf: 'fzf',
      pacman: 'fzf',
      zypper: 'fzf',
    },
  },
  {
    id: 'ripgrep',
    name: 'ripgrep',
    description: 'Fast recursive search tool',
    category: 'CLI Tools',
    iconUrl: 'https://api.iconify.design/mdi/text-search.svg?color=%23C0C0C0',
    targets: {
      winget: 'BurntSushi.ripgrep.MSVC',
      chocolatey: 'ripgrep',
      scoop: 'ripgrep',
      homebrew: 'ripgrep',
      macports: 'ripgrep',
      apt: 'ripgrep',
      dnf: 'ripgrep',
      pacman: 'ripgrep',
      zypper: 'ripgrep',
    },
  },
  {
    id: 'jq',
    name: 'jq',
    description: 'Command-line JSON processor',
    category: 'CLI Tools',
    iconUrl: 'https://api.iconify.design/simple-icons/json.svg?color=%23000000',
    targets: {
      winget: 'jqlang.jq',
      chocolatey: 'jq',
      scoop: 'jq',
      homebrew: 'jq',
      macports: 'jq',
      apt: 'jq',
      dnf: 'jq',
      pacman: 'jq',
      zypper: 'jq',
    },
  },
  {
    id: 'btop',
    name: 'btop',
    description: 'Beautiful terminal resource monitor with graphs',
    category: 'CLI Tools',
    iconUrl: 'https://api.iconify.design/mdi/monitor-dashboard.svg?color=%23FF6B6B',
    targets: {
      winget: 'aristocratos.btop4win',
      chocolatey: 'btop4win',
      homebrew: 'btop',
      macports: 'btop',
      apt: 'btop',
      dnf: 'btop',
      pacman: 'btop',
      zypper: 'btop',
      snap: 'btop',
    },
  },
  {
    id: 'htop',
    name: 'htop',
    description: 'Interactive process viewer and system monitor',
    category: 'CLI Tools',
    iconUrl: 'https://api.iconify.design/mdi/chart-bar.svg?color=%234CE026',
    targets: {
      homebrew: 'htop',
      macports: 'htop',
      apt: 'htop',
      dnf: 'htop',
      pacman: 'htop',
      zypper: 'htop',
      snap: 'htop',
    },
    unavailableReason: 'Unix/Linux-only application. Not available for Windows.',
  },
  {
    id: 'bat',
    name: 'bat',
    description: 'Cat clone with syntax highlighting and git integration',
    category: 'CLI Tools',
    iconUrl: 'https://api.iconify.design/mdi/file-code-outline.svg?color=%23A6E22E',
    targets: {
      winget: 'sharkdp.bat',
      chocolatey: 'bat',
      scoop: 'bat',
      homebrew: 'bat',
      macports: 'bat',
      apt: 'bat',
      dnf: 'bat',
      pacman: 'bat',
      zypper: 'bat',
    },
  },
  {
    id: 'eza',
    name: 'eza',
    description: 'Modern ls replacement with colors and icons',
    category: 'CLI Tools',
    iconUrl: 'https://api.iconify.design/mdi/format-list-bulleted.svg?color=%23F9E64F',
    targets: {
      winget: 'eza-community.eza',
      chocolatey: 'eza',
      scoop: 'eza',
      homebrew: 'eza',
      apt: 'eza',
      pacman: 'eza',
      zypper: 'eza',
    },
    unavailableReason: 'Not in Fedora repos. CLI-only (no Flatpak/Snap).',
  },
  {
    id: 'zoxide',
    name: 'zoxide',
    description: 'Smart cd that learns your habits',
    category: 'CLI Tools',
    iconUrl: 'https://api.iconify.design/mdi/folder-move-outline.svg?color=%23FF9F43',
    targets: {
      winget: 'ajeetdsouza.zoxide',
      chocolatey: 'zoxide',
      scoop: 'zoxide',
      homebrew: 'zoxide',
      apt: 'zoxide',
      dnf: 'zoxide',
      pacman: 'zoxide',
      zypper: 'zoxide',
    },
  },
  {
    id: 'fd',
    name: 'fd',
    description: 'Simple, fast alternative to find command',
    category: 'CLI Tools',
    iconUrl: 'https://api.iconify.design/mdi/file-search-outline.svg?color=%2356BE89',
    targets: {
      winget: 'sharkdp.fd',
      chocolatey: 'fd',
      scoop: 'fd',
      homebrew: 'fd',
      macports: 'fd',
      apt: 'fd-find',
      dnf: 'fd-find',
      pacman: 'fd',
      zypper: 'fd',
    },
  },
  {
    id: 'tmux',
    name: 'tmux',
    description: 'Terminal session manager and multiplexer',
    category: 'CLI Tools',
    iconUrl: 'https://api.iconify.design/simple-icons/tmux.svg?color=%231BB91F',
    targets: {
      chocolatey: 'tmux',
      homebrew: 'tmux',
      macports: 'tmux',
      apt: 'tmux',
      dnf: 'tmux',
      pacman: 'tmux',
      zypper: 'tmux',
    },
  },
  {
    id: 'wget',
    name: 'wget',
    description: 'Command-line file downloader for HTTP/FTP',
    category: 'CLI Tools',
    iconUrl: 'https://api.iconify.design/mdi/download.svg?color=%233FA75E',
    targets: {
      winget: 'JernejSimoncic.Wget',
      chocolatey: 'wget',
      scoop: 'wget',
      homebrew: 'wget',
      macports: 'wget',
      apt: 'wget',
      dnf: 'wget',
      pacman: 'wget',
      zypper: 'wget',
    },
  },
  {
    id: 'curl',
    name: 'curl',
    description: 'Command-line tool for transferring data via URLs',
    category: 'CLI Tools',
    iconUrl: 'https://api.iconify.design/simple-icons/curl.svg?color=%23073551',
    targets: {
      winget: 'cURL.cURL',
      chocolatey: 'curl',
      scoop: 'curl',
      homebrew: 'curl',
      macports: 'curl',
      apt: 'curl',
      dnf: 'curl',
      pacman: 'curl',
      zypper: 'curl',
    },
  },
  {
    id: 'ncdu',
    name: 'ncdu',
    description: 'NCurses-based disk usage analyzer',
    category: 'CLI Tools',
    iconUrl: 'https://api.iconify.design/mdi/chart-arc.svg?color=%2300ADEE',
    targets: {
      chocolatey: 'ncdu',
      homebrew: 'ncdu',
      macports: 'ncdu',
      apt: 'ncdu',
      dnf: 'ncdu',
      pacman: 'ncdu',
      zypper: 'ncdu',
    },
  },
  {
    id: 'rsync',
    name: 'rsync',
    description: 'Fast incremental file transfer and sync tool',
    category: 'CLI Tools',
    iconUrl: 'https://api.iconify.design/mdi/sync.svg?color=%232ECC71',
    targets: {
      chocolatey: 'rsync',
      homebrew: 'rsync',
      macports: 'rsync',
      apt: 'rsync',
      dnf: 'rsync',
      pacman: 'rsync',
      zypper: 'rsync',
    },
  },

  // VPN & Network
  {
    id: 'tailscale',
    name: 'Tailscale',
    description: 'Zero-config VPN built on WireGuard',
    category: 'VPN & Network',
    iconUrl: 'https://api.iconify.design/simple-icons/tailscale.svg?color=%23242424',
    targets: {
      winget: 'Tailscale.Tailscale',
      chocolatey: 'tailscale',
      scoop: 'tailscale',
      homebrew: 'tailscale',
      macports: 'tailscale',
      pacman: 'tailscale',
      dnf: 'tailscale',
      zypper: 'tailscale',
    },
    unavailableReason: 'Not in Debian or Ubuntu repos. Follow instructions at [tailscale.com/download/linux](https://tailscale.com/download/linux).',
  },
  {
    id: 'wireguard',
    name: 'WireGuard',
    description: 'Fast and modern VPN protocol',
    category: 'VPN & Network',
    iconUrl: 'https://api.iconify.design/simple-icons/wireguard.svg?color=%2388171A',
    targets: {
      winget: 'WireGuard.WireGuard',
      chocolatey: 'wireguard',
      scoop: 'wireguard',
      homebrew: 'wireguard-tools',
      macports: 'wireguard-tools',
      apt: 'wireguard',
      dnf: 'wireguard-tools',
      pacman: 'wireguard-tools',
      zypper: 'wireguard-tools',
    },
  },
  {
    id: 'protonvpn',
    name: 'Proton VPN',
    description: 'Secure VPN by the makers of ProtonMail',
    category: 'VPN & Network',
    iconUrl: 'https://api.iconify.design/simple-icons/protonvpn.svg?color=%236D4AFF',
    targets: {
      winget: 'ProtonTechnologies.ProtonVPN',
      chocolatey: 'protonvpn',
      homebrew: '--cask protonvpn',
      pacman: 'proton-vpn-gtk-app',
      flatpak: 'com.protonvpn.www',
    },
    unavailableReason: 'Not in official Linux distro repos. Use [Flatpak](https://flathub.org/apps/com.protonvpn.www) or download from [protonvpn.com](https://protonvpn.com/support/linux-vpn-setup/).',
  },
  {
    id: 'mullvad',
    name: 'Mullvad VPN',
    description: 'Privacy-focused VPN with no-logging policy',
    category: 'VPN & Network',
    iconUrl: 'https://api.iconify.design/simple-icons/mullvad.svg?color=%2344AD4D',
    targets: {
      winget: 'MullvadVPN.MullvadVPN',
      chocolatey: 'mullvad-app',
      homebrew: '--cask mullvad-vpn',
      pacman: 'mullvad-vpn-bin',
    },
    unavailableReason: 'Not in official Linux distro repos. Download from [mullvad.net](https://mullvad.net/en/download).',
  },
  {
    id: 'wireshark',
    name: 'Wireshark',
    description: 'Network protocol analyzer',
    category: 'VPN & Network',
    iconUrl: 'https://api.iconify.design/simple-icons/wireshark.svg?color=%231679A7',
    targets: {
      winget: 'WiresharkFoundation.Wireshark',
      chocolatey: 'wireshark',
      scoop: 'wireshark',
      homebrew: '--cask wireshark',
      macports: 'wireshark',
      apt: 'wireshark',
      dnf: 'wireshark',
      pacman: 'wireshark-qt',
      zypper: 'wireshark',
      flatpak: 'org.wireshark.Wireshark',
    },
  },
  {
    id: 'openvpn',
    name: 'OpenVPN',
    description: 'Full-featured SSL VPN solution',
    category: 'VPN & Network',
    iconUrl: 'https://api.iconify.design/simple-icons/openvpn.svg?color=%23EA7E20',
    targets: {
      winget: 'OpenVPNTechnologies.OpenVPN',
      chocolatey: 'openvpn',
      scoop: 'openvpn',
      homebrew: 'openvpn',
      macports: 'openvpn',
      apt: 'openvpn',
      dnf: 'openvpn',
      pacman: 'openvpn',
      zypper: 'openvpn',
    },
  },
  {
    id: 'nmap',
    name: 'Nmap',
    description: 'Network discovery and security auditing tool',
    category: 'VPN & Network',
    iconUrl: 'https://api.iconify.design/mdi/radar.svg?color=%234682B4',
    targets: {
      winget: 'Insecure.Nmap',
      chocolatey: 'nmap',
      scoop: 'nmap',
      homebrew: 'nmap',
      macports: 'nmap',
      apt: 'nmap',
      dnf: 'nmap',
      pacman: 'nmap',
      zypper: 'nmap',
    },
  },
  
  // Security
  {
    id: 'bitwarden',
    name: 'Bitwarden',
    description: 'Open-source password manager',
    category: 'Security',
    iconUrl: 'https://api.iconify.design/simple-icons/bitwarden.svg?color=%23175DDC',
    targets: {
      winget: 'Bitwarden.Bitwarden',
      chocolatey: 'bitwarden',
      scoop: 'bitwarden',
      homebrew: '--cask bitwarden',
      pacman: 'bitwarden',
      flatpak: 'com.bitwarden.desktop',
      snap: 'bitwarden',
    },
    unavailableReason: 'Not in official Linux distro repos. Use [Flatpak](https://flathub.org/apps/com.bitwarden.desktop), [Snap](https://snapcraft.io/bitwarden), or download from [bitwarden.com](https://bitwarden.com/download/).',
  },
  {
    id: '1password',
    name: '1Password',
    description: 'Premium password manager',
    category: 'Security',
    iconUrl: 'https://api.iconify.design/simple-icons/1password.svg?color=%230094F5',
    targets: {
      winget: 'AgileBits.1Password',
      chocolatey: '1password',
      scoop: '1password',
      homebrew: '--cask 1password',
      pacman: '1password',
      flatpak: 'com.onepassword.OnePassword',
      snap: '1password',
    },
    unavailableReason: 'Not in official Linux distro repos or MacPorts. Use [Flatpak](https://flathub.org/apps/com.onepassword.OnePassword), [Snap](https://snapcraft.io/1password), or download from [1password.com](https://1password.com/downloads/).',
  },
  {
    id: 'keepassxc',
    name: 'KeePassXC',
    description: 'Cross-platform password manager',
    category: 'Security',
    iconUrl: 'https://api.iconify.design/simple-icons/keepassxc.svg?color=%236CAC4D',
    targets: {
      winget: 'KeePassXCTeam.KeePassXC',
      chocolatey: 'keepassxc',
      scoop: 'keepassxc',
      homebrew: '--cask keepassxc',
      macports: 'KeePassXC',
      apt: 'keepassxc',
      dnf: 'keepassxc',
      pacman: 'keepassxc',
      zypper: 'keepassxc',
      flatpak: 'org.keepassxc.KeePassXC',
      snap: 'keepassxc',
    },
  },
  {
    id: 'gpg',
    name: 'GPG Suite',
    description: 'OpenPGP encryption tools',
    category: 'Security',
    iconUrl: 'https://api.iconify.design/simple-icons/gnuprivacyguard.svg?color=%230093DD',
    targets: {
      winget: 'GnuPG.Gpg4win',
      chocolatey: 'gpg4win',
      scoop: 'gpg',
      homebrew: 'gnupg',
      macports: 'gnupg2',
      apt: 'gnupg',
      dnf: 'gnupg2',
      pacman: 'gnupg',
      zypper: 'gpg2',
    },
  },
  {
    id: 'veracrypt',
    name: 'VeraCrypt',
    description: 'Free disk encryption based on TrueCrypt',
    category: 'Security',
    iconUrl: 'https://api.iconify.design/mdi/lock.svg?color=%23009933',
    targets: {
      winget: 'IDRIX.VeraCrypt',
      chocolatey: 'veracrypt',
      scoop: 'veracrypt',
      homebrew: '--cask veracrypt',
      pacman: 'veracrypt',
      zypper: 'veracrypt',
    },
    unavailableReason: 'Not in official Debian/Ubuntu/Fedora repos. Download from [veracrypt.fr](https://veracrypt.fr/en/Downloads.html).',
  },
  {
    id: 'clamav',
    name: 'ClamAV',
    description: 'Open-source antivirus engine for malware detection',
    category: 'Security',
    iconUrl: 'https://api.iconify.design/mdi/shield-check.svg?color=%23CC0000',
    targets: {
      winget: 'ClamAV.ClamAV',
      chocolatey: 'clamav',
      homebrew: 'clamav',
      macports: 'clamav',
      apt: 'clamav',
      dnf: 'clamav',
      pacman: 'clamav',
      zypper: 'clamav',
    },
  },
  
  // File Sharing
  {
    id: 'syncthing',
    name: 'Syncthing',
    description: 'Continuous file synchronization',
    category: 'File Sharing',
    iconUrl: 'https://api.iconify.design/simple-icons/syncthing.svg?color=%230891D1',
    targets: {
      winget: 'Syncthing.Syncthing',
      chocolatey: 'syncthing',
      scoop: 'syncthing',
      homebrew: 'syncthing',
      macports: 'syncthing',
      apt: 'syncthing',
      dnf: 'syncthing',
      pacman: 'syncthing',
      zypper: 'syncthing',
      flatpak: 'me.kozec.syncthingtk',
      snap: 'syncthing',
    },
  },
  {
    id: 'qbittorrent',
    name: 'qBittorrent',
    description: 'Free and open-source BitTorrent client',
    category: 'File Sharing',
    iconUrl: 'https://api.iconify.design/simple-icons/qbittorrent.svg?color=%232F67BA',
    targets: {
      winget: 'qBittorrent.qBittorrent',
      chocolatey: 'qbittorrent',
      scoop: 'qbittorrent',
      homebrew: '--cask qbittorrent',
      macports: 'qBittorrent',
      apt: 'qbittorrent',
      dnf: 'qbittorrent',
      pacman: 'qbittorrent',
      zypper: 'qbittorrent',
      flatpak: 'org.qbittorrent.qBittorrent',
      snap: 'qbittorrent-arnatious',
    },
  },
  {
    id: 'transmission',
    name: 'Transmission',
    description: 'Lightweight BitTorrent client',
    category: 'File Sharing',
    iconUrl: 'https://api.iconify.design/simple-icons/transmission.svg?color=%23D70000',
    targets: {
      winget: 'Transmission.Transmission',
      chocolatey: 'transmission',
      homebrew: '--cask transmission',
      apt: 'transmission',
      dnf: 'transmission',
      pacman: 'transmission-gtk',
      zypper: 'transmission',
      flatpak: 'com.transmissionbt.Transmission',
    },
  },
  {
    id: 'filezilla',
    name: 'FileZilla',
    description: 'FTP, FTPS and SFTP client',
    category: 'File Sharing',
    iconUrl: 'https://api.iconify.design/simple-icons/filezilla.svg?color=%23BF0000',
    targets: {
      winget: 'TimKosse.FileZilla.Client',
      chocolatey: 'filezilla',
      scoop: 'filezilla',
      homebrew: '--cask filezilla',
      macports: 'filezilla',
      apt: 'filezilla',
      dnf: 'filezilla',
      pacman: 'filezilla',
      zypper: 'filezilla',
      flatpak: 'org.filezillaproject.Filezilla',
    },
  },
  {
    id: 'localsend',
    name: 'LocalSend',
    description: 'Cross-platform AirDrop alternative for local sharing',
    category: 'File Sharing',
    iconUrl: 'https://api.iconify.design/simple-icons/localsend.svg?color=%23FCA73C',
    targets: {
      winget: 'LocalSend.LocalSend',
      chocolatey: 'localsend',
      scoop: 'localsend',
      homebrew: '--cask localsend',
      pacman: 'localsend-bin',
      flatpak: 'org.localsend.localsend_app',
    },
    unavailableReason: 'Not in official Linux distro repos. Use [Flatpak](https://flathub.org/apps/org.localsend.localsend_app) or download from [localsend.org](https://localsend.org/download).',
  },
  {
    id: 'nextcloud',
    name: 'Nextcloud',
    description: 'Self-hosted cloud storage sync client',
    category: 'File Sharing',
    iconUrl: 'https://api.iconify.design/simple-icons/nextcloud.svg?color=%230082C9',
    targets: {
      winget: 'Nextcloud.NextcloudDesktop',
      chocolatey: 'nextcloud-client',
      scoop: 'nextcloud',
      homebrew: '--cask nextcloud',
      apt: 'nextcloud-desktop',
      dnf: 'nextcloud-client',
      pacman: 'nextcloud-client',
      zypper: 'nextcloud-desktop',
      flatpak: 'com.nextcloud.desktopclient.nextcloud',
      snap: 'nextcloud-desktop-client',
    },
  },
  {
    id: 'dropbox',
    name: 'Dropbox',
    description: 'Popular cloud file storage and sync service',
    category: 'File Sharing',
    iconUrl: 'https://api.iconify.design/simple-icons/dropbox.svg?color=%230061FF',
    targets: {
      winget: 'Dropbox.Dropbox',
      chocolatey: 'dropbox',
      scoop: 'dropbox',
      homebrew: '--cask dropbox',
      pacman: 'dropbox',
      flatpak: 'com.dropbox.Client',
    },
    unavailableReason: 'Not in official Linux distro repos. Use [Flatpak](https://flathub.org/apps/com.dropbox.Client) or download from [dropbox.com](https://www.dropbox.com/install).',
  },

  // System
  {
    id: 'htop',
    name: 'htop',
    description: 'Interactive process viewer',
    category: 'System',
    iconUrl: 'https://api.iconify.design/mdi/chart-bar.svg?color=%234CE026',
    targets: {
      homebrew: 'htop',
      macports: 'htop',
      apt: 'htop',
      dnf: 'htop',
      pacman: 'htop',
      zypper: 'htop',
      snap: 'htop',
    },
    unavailableReason: 'Unix/Linux-only application. Not available for Windows.',
  },
  {
    id: 'neofetch',
    name: 'Neofetch',
    description: 'System information tool',
    category: 'System',
    iconUrl: 'https://api.iconify.design/mdi/console.svg?color=%2357F287',
    targets: {
      scoop: 'neofetch',
      homebrew: 'neofetch',
      macports: 'neofetch',
      apt: 'neofetch',
      dnf: 'neofetch',
      pacman: 'neofetch',
      zypper: 'neofetch',
      snap: 'neofetch',
    },
  },
  {
    id: 'fastfetch',
    name: 'fastfetch',
    description: 'Fast neofetch-like system info tool',
    category: 'System',
    iconUrl: 'https://api.iconify.design/mdi/console.svg?color=%2357F287',
    targets: {
      winget: 'Fastfetch-cli.Fastfetch',
      chocolatey: 'fastfetch',
      scoop: 'fastfetch',
      homebrew: 'fastfetch',
      apt: 'fastfetch',
      dnf: 'fastfetch',
      pacman: 'fastfetch',
      zypper: 'fastfetch',
    },
  },
  {
    id: 'timeshift',
    name: 'Timeshift',
    description: 'System restore utility',
    category: 'System',
    iconUrl: 'https://api.iconify.design/mdi/backup-restore.svg?color=%23D9534F',
    targets: {
      apt: 'timeshift',
      dnf: 'timeshift',
      pacman: 'timeshift',
      zypper: 'timeshift',
    },
    unavailableReason: 'Linux-only application. Not available for Windows or macOS.',
  },
  {
    id: 'gparted',
    name: 'GParted',
    description: 'GNOME partition editor for disk management',
    category: 'System',
    iconUrl: 'https://api.iconify.design/simple-icons/gnome.svg?color=%23E95420',
    targets: {
      apt: 'gparted',
      dnf: 'gparted',
      pacman: 'gparted',
      zypper: 'gparted',
    },
    unavailableReason: 'Linux-only application. GParted requires root access and is not available via Flatpak or Snap.',
  },
  {
    id: 'flameshot',
    name: 'Flameshot',
    description: 'Powerful screenshot tool with annotation',
    category: 'System',
    iconUrl: 'https://api.iconify.design/mdi/camera.svg?color=%23FF6B6B',
    targets: {
      winget: 'Flameshot.Flameshot',
      chocolatey: 'flameshot',
      scoop: 'flameshot',
      homebrew: '--cask flameshot',
      apt: 'flameshot',
      dnf: 'flameshot',
      pacman: 'flameshot',
      zypper: 'flameshot',
      flatpak: 'org.flameshot.Flameshot',
    },
  },
  {
    id: 'bleachbit',
    name: 'BleachBit',
    description: 'Free disk space and maintain privacy',
    category: 'System',
    iconUrl: 'https://api.iconify.design/mdi/broom.svg?color=%23FF6B6B',
    targets: {
      winget: 'BleachBit.BleachBit',
      chocolatey: 'bleachbit',
      scoop: 'bleachbit',
      homebrew: '--cask bleachbit',
      apt: 'bleachbit',
      dnf: 'bleachbit',
      pacman: 'bleachbit',
      zypper: 'bleachbit',
      flatpak: 'org.bleachbit.BleachBit',
    },
  },
  {
    id: 'kdeconnect',
    name: 'KDE Connect',
    description: 'Connect your phone to your desktop',
    category: 'System',
    iconUrl: 'https://api.iconify.design/simple-icons/kde.svg?color=%23338BDB',
    targets: {
      winget: 'KDE.KDEConnect',
      chocolatey: 'kdeconnect-kde',
      homebrew: '--cask kde-connect',
      apt: 'kdeconnect',
      dnf: 'kdeconnectd',
      pacman: 'kdeconnect',
      zypper: 'kdeconnect-kde',
    },
  },
  {
    id: 'borgbackup',
    name: 'BorgBackup',
    description: 'Deduplicating backup program with compression',
    category: 'System',
    iconUrl: 'https://api.iconify.design/simple-icons/borgbackup.svg?color=%2300B041',
    targets: {
      winget: 'BorgBackup.BorgBackup',
      chocolatey: 'borgbackup',
      homebrew: 'borgbackup',
      macports: 'borgbackup',
      apt: 'borgbackup',
      dnf: 'borgbackup',
      pacman: 'borg',
      zypper: 'borgbackup',
    },
  },
  {
    id: 'restic',
    name: 'Restic',
    description: 'Fast, secure, efficient backup program',
    category: 'System',
    iconUrl: 'https://api.iconify.design/mdi/cloud-sync.svg?color=%2300B4AB',
    targets: {
      winget: 'restic.restic',
      chocolatey: 'restic',
      scoop: 'restic',
      homebrew: 'restic',
      macports: 'restic',
      apt: 'restic',
      dnf: 'restic',
      pacman: 'restic',
      zypper: 'restic',
    },
  },
];

// Helper Functions

/**
 * Get apps filtered by category
 */
export function getAppsByCategory(category: Category): AppData[] {
  return apps.filter(app => app.category === category);
}

/**
 * Get the color for a category
 */
export function getCategoryColor(category: Category): string {
  return categoryColors[category] || '#6b7280';
}

/**
 * Get OS by ID
 */
export function getOSById(id: OSId): OS | undefined {
  return operatingSystems.find(os => os.id === id);
}

/**
 * Check if an app is available for a given package manager
 */
export function isAppAvailableForPackageManager(app: AppData, packageManagerId: PackageManagerId): boolean {
  const target = app.targets[packageManagerId];
  return target !== undefined && target !== '';
}

/**
 * Check if an app is available for a given OS (has at least one package manager target for that OS)
 * @deprecated Use isAppAvailableForPackageManager instead for more precise availability checking
 */
export function isAppAvailableForOS(app: AppData, osId: OSId): boolean {
  const osPackageManagers = getPackageManagersByOS(osId);
  return osPackageManagers.some(pm => isAppAvailableForPackageManager(app, pm.id));
}

// Package Manager Helper Functions - Requirements 1.1, 1.2, 2.1

/**
 * Get package managers filtered by operating system
 */
export function getPackageManagersByOS(osId: OSId): PackageManager[] {
  return packageManagers.filter(pm => pm.osId === osId);
}

/**
 * Get a package manager by its ID
 */
export function getPackageManagerById(id: PackageManagerId): PackageManager | undefined {
  return packageManagers.find(pm => pm.id === id);
}

/**
 * Get the primary (default) package manager for an operating system
 */
export function getPrimaryPackageManager(osId: OSId): PackageManager {
  const primary = packageManagers.find(pm => pm.osId === osId && pm.isPrimary);
  if (primary) {
    return primary;
  }
  // Fallback to first package manager for the OS if no primary is set
  const fallback = packageManagers.find(pm => pm.osId === osId);
  if (!fallback) {
    throw new Error(`No package manager found for OS: ${osId}`);
  }
  return fallback;
}

// LocalStorage Keys
export const STORAGE_KEYS = {
  SELECTED_OS: 'packmate-os',
  SELECTED_APPS: 'packmate-apps',
  THEME: 'packmate-theme',
  // New: per-OS package manager selection - Requirements 2.3
  PACKAGE_MANAGER_WINDOWS: 'packmate-pm-windows',
  PACKAGE_MANAGER_MACOS: 'packmate-pm-macos',
  PACKAGE_MANAGER_LINUX: 'packmate-pm-linux',
} as const;
